### ISSUE TITLE
ensime-server won't compile with 2.11.3 and later

### ISSUE THREAD

**Issue by marcsaegesser** [ensime/ensime-server#678]
I just tested building ensime-server using the staged version of 2.11.4 and discovered that it won't compile. It turns out the problem actually began in 2.11.3 but I missed testing that release.

The `invalidateClassPathEntries` method was removed from nsc/Global.scala (along with all the other invalidation code) with a statement that the code was originally added as an experiment that has since been abandoned and thus the code was unused and not going to be maintained. I posted this on the scala-internals mailing list but I doubt this code will come back.

@edani You added this code on 9/21/2014. Is there any way we can work around this?

[error] /home/msaegesser/work/ensime-server/src/main/scala/org/ensime/server/RichPresentationCompiler.scala:200: not found: value invalidateClassPathEntries
[error]     invalidateClassPathEntries(f.getCanonicalPath())
[error]     ^
[error] one error found
[error](compile:compile) Compilation failed
[error] Total time: 57 s, completed Oct 27, 2014 3:30:30 PM
